=== IgorRodchenkov/pathway-commons.cpath1/cpath/testData/externalDb/external_db.dtd
<!-- 
     DTD for Storing/Exchanging External Databases used by cPath. 
    The DTD is primarily used to import / export a list of external databases used by cPath,
    but may be useful to other third-party applications as well.
    
     DTD created by Ethan Cerami:  cerami AT cbio.mskcc.org
-->

<!--
    A database list consists of one or more external databases
-->
<!ELEMENT external_database_list (external_database)+>

<!-- 
    Each database must have a name, description, a url pattern, and a 
    list of controlled vocabulary terms.
-->
<!ELEMENT external_database (name, description, 
    url?, controlled_terms)>
    
<!-- 
     We currectly support two type of databases:  PROTEIN_UNIFICATION and
    LINK_OUT.  PROTEIN_UNIFICATION databases are used to determine equivalence
    or identity or proteins, whereas LINK_OUT database are used to provide links out to
    other types of data.  For example, SWISS PROT is a PROTEIN_UNIFICATION
    database, wheras PubMed is a LINK_OUT database.
-->    
<!ATTLIST external_database type 
    (PROTEIN_UNIFICATION | LINK_OUT) #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>


<!-- 
    The URL Pattern is a String pattern that enables direct linking to the database.
    cPath explicitly replaces the %ID% pattern with an actual ID to generate live links.

    For example, given the URL pattern: http://www.pir.uniprot.org/cgi-bin/upEntry?id=%ID%
    and a saple ID of P08913, cPath generates the live URL as:
    http://www.pir.uniprot.org/cgi-bin/upEntry?id=P08913 
    
    If you have a url_pattern, you must also specify a sample_id.  The url pattern plus
    the sample_id can be used to automatically verify that the links actually work.
    This is important, as database providers may modify their linking rules at any time,
    and not inform us of the change.
-->
<!ELEMENT url (url_pattern, sample_id) >
<!ELEMENT url_pattern (#PCDATA)>
<!ELEMENT sample_id (#PCDATA)>

<!-- 
    The controlled_term elements are used to map multiple names to a single database. 
    For example, some sources use "SWP" to refer to SWISS-PROT;  other sources use
    "SWISS-PROT;  and still others use "UNIPROT".  By maintaining a list of terms, we can
    accurately map multiple names to a single database.
    
    master_term refers to the database name that we output from cPath.
    synonym refers to an equivalent database name that we accept as input to cPath.

    For example, if an external file specifies SWP (a synonym)  we normalize it to 
     UNI-PROT (master term).  When we output this data via the cPath web site, or via the
     cPath web service, the term will appear as UNI_PROT.
     
    Note that controlled_term items are treated as case insensitive.  Therefore, a synonym
    of SWP would be accepted by cPath as swp, SWp, etc.  
-->
<!ELEMENT controlled_terms (master_term, synonym*)>
<!ELEMENT master_term (#PCDATA)>
<!ELEMENT synonym (#PCDATA) >

=== IgorRodchenkov/pathway-commons.cpath1/cpath/dbData/externalDb/external_db.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE external_database_list SYSTEM "external_db.dtd">
<external_database_list>
    <!-- 
    ###################################################################
    List of PROTEIN_UNIFICATION Databases 
    ###################################################################    
    -->
    
    <!--  
        SWISS-PROT / UNI-PROT
    -->
    <external_database type="PROTEIN_UNIFICATION">
        <name>UniProt</name>
        <description>Universal Protein Resource (UniProt)</description>
        <entity_url>
            <url_pattern>http://www.ebi.uniprot.org/entry/%ID%</url_pattern>
            <sample_id>P31947</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>UNIPROT</master_term>
            <synonym>SWISS-PROT</synonym>
            <synonym>SWISSPROT</synonym>
            <synonym>SWISSTREMBL</synonym>
            <synonym>SWP</synonym>
            <synonym>SWISS-PROT/TREMBL</synonym>
        </controlled_terms>
    </external_database>

    <!--
        PIR
    -->
    <external_database type="PROTEIN_UNIFICATION">
        <name>PIR</name>
        <description>The Protein Information Resource (PIR)</description>
        <entity_url>
            <url_pattern>http://pir.georgetown.edu/cgi-bin/nbrfget?uid=%ID%</url_pattern>
            <sample_id>NF01438533</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>PIR</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        InterPro
    -->
    <external_database type="PROTEIN_UNIFICATION">
        <name>InterPro</name>
        <description>InterPro database of protein families, domains and functional sites</description>
        <entity_url>
            <url_pattern>http://www.ebi.ac.uk/interpro/DisplayIproEntry?ac=%ID%</url_pattern>
            <sample_id>IPR000427</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>INTERPRO</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        HUGE
    -->
    <external_database type="PROTEIN_UNIFICATION">
        <name>HUGE</name>
        <description>HUGE Protein Database</description>
        <entity_url>
            <url_pattern>http://www.kazusa.or.jp/huge/gfpage/%ID%/</url_pattern>
            <sample_id>KIAA0054</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term></master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
    ###################################################################    
    List of LINK_OUT Databases 
    ###################################################################
    -->
    
    <!-- 
        PROSITE
    -->
    <external_database type="LINK_OUT">
        <name>PROSITE</name>
        <description>PROSITE database of protein families and domains</description>
        <entity_url>
            <url_pattern>http://us.expasy.org/cgi-bin/nicedoc.pl?%ID%</url_pattern>
            <sample_id>PDOC50088</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>PROSITE</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        NCBI Entrez Gene
    -->
    <external_database type="LINK_OUT">
        <name>Entrez Gene</name>
        <description>NCBI Entrez Gene</description>
        <entity_url>
            <url_pattern>http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=gene&amp;cmd=search&amp;term=%ID%</url_pattern>
            <sample_id>p53</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>ENTREZ_GENE</master_term>
            <synonym>LOCUSLINK</synonym>
            <synonym>LOCUS_LINK</synonym>
            <synonym>LOCUS-LINK</synonym>
        </controlled_terms>
    </external_database>
    
    <!-- 
        NCBI Pub Med
    -->
    <external_database type="LINK_OUT">
        <name>PubMed</name>
        <description>NCBI PubMed</description>
        <entity_url>
            <url_pattern>http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=%ID%&amp;dopt=Abstract</url_pattern>
            <sample_id>14597658 </sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>PUBMED</master_term>
            <synonym>PMID</synonym>
        </controlled_terms>
    </external_database>
    
    <!--  
        NCBI UniGene
    -->
    <external_database type="LINK_OUT">
        <name>UniGene</name>
        <description>NCBI UniGene Database</description>
        <entity_url>
            <url_pattern>http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=unigene&amp;cmd=search&amp;term=%ID%</url_pattern>
            <sample_id>p53</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>UNIGENE</master_term>
        </controlled_terms>
    </external_database>
    
    <!--
        NCBI OMIM
    -->
    <external_database type="LINK_OUT">
        <name>OMIM</name>
        <description>Online Mendelian Inheritance in Man (OMIM)</description>
        <entity_url>
            <url_pattern>http://www.ncbi.nlm.nih.gov/entrez/dispomim.cgi?id=%ID%</url_pattern>
            <sample_id>222100</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>OMIM</master_term>
        </controlled_terms>
    </external_database>
    
    <!--
        PROSITE
    -->
    <external_database type="LINK_OUT">
        <name>PROSITE</name>
        <description>PROSITE database of protein families and domains</description>
        <entity_url>
            <url_pattern>http://us.expasy.org/cgi-bin/nicedoc.pl?%ID%</url_pattern>
            <sample_id>PDOC50138</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>PROSITE</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        Database of Interacting Proteins (DIP)
    -->
    <external_database type="LINK_OUT">
        <name>DIP</name>
        <description>Database of Interacting Proteins (DIP)&apos;</description>
        <entity_url>
            <url_pattern>http://dip.doe-mbi.ucla.edu/dip/Search.cgi?SM=3&amp;AC=DIP:%ID&amp;Search2=Query+DIP</url_pattern>
            <sample_id>24197</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>DIP</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        Pfam 
    -->
    <external_database type="LINK_OUT">
        <name>Pfam</name>
        <description>Pfam protein families database of alignments and hidden Markov models</description>
        <entity_url>
            <url_pattern>http://www.sanger.ac.uk/cgi-bin/Pfam/getacc?%ID%</url_pattern>
            <sample_id>PF00870</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>PFAM</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        Gene Ontology
    -->
    <external_database type="LINK_OUT">
        <name>GO</name>
        <description>Gene Ontology (GO)</description>
        <entity_url>
            <url_pattern>http://www.godatabase.org/cgi-bin/amigo/go.cgi?open_1=%ID%</url_pattern>
            <sample_id>0006915</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>GO</master_term>
            <synonym>GENE ONTOLOGY</synonym>
        </controlled_terms>
    </external_database>
    
    <!--  
        Affymetrix.
        Unfortunately, there is currently no public URL for viewing Affymetrix IDs.
    -->
    <external_database type="LINK_OUT">
        <name>Affymetrix</name>
        <description>Affymetrix</description>
        <controlled_terms>
            <master_term>AFFYMETRIX</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        IntAct
    -->
    <external_database type="LINK_OUT">
        <name>IntAct</name>
        <description>IntAct database of protein interaction data</description>
        <entity_url>
		    <url_pattern>http://www.ebi.ac.uk/intact/search/do/search?searchString=%ID%</url_pattern>
            <sample_id>EBI-366083</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>INTACT</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        FlyBase
    -->
    <external_database type="LINK_OUT">
        <name>FlyBase</name>
        <description>FlyBase is a comprehensive database for information on the genetics and molecular biology of Drosophila</description>
        <entity_url>
            <url_pattern>http://flybase.bio.indiana.edu/.bin/fbidq.html?%ID%</url_pattern>
            <sample_id>FBgn0000015</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>FLYBASE</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        PDB
    -->
    <external_database type="LINK_OUT">
        <name>PDB</name>
        <description>Protein Data Bank (PDB)</description>
        <entity_url>
            <url_pattern>http://www.rcsb.org/pdb/cgi/explore.cgi?pdbId=%ID%</url_pattern>
            <sample_id>12CA</sample_id>
        </entity_url>
        <controlled_terms>
            <master_term>PDB</master_term>
        </controlled_terms>
    </external_database>
    
    <!-- 
        SGD
    -->
    <external_database type="LINK_OUT">
        <name>SGD</name>
        <description>Saccharomyces Genome Database (SGD)</description>
        <entity_url>
            <url_pattern>http://db.yeastgenome.org/cgi-bin/locus.pl?locus=%ID%></url_pattern>
            <sample_id>YDR217C</sample_id>
        </entity_url>
        <controlled_terms>
